export const BOOKMARK_ADD_ITEM_FAIL = 'BOOKMARK_ADD_ITEM_FAIL';
export const BOOKMARK_ADD_ITEM = 'BOOKMARK_ADD_ITEM';
export const BOOKMARK_REMOVE_ITEM = 'BOOKMARK_REMOVE_ITEM';
export const BOOKMARK_SAVE_SHIPPING_ADDRESS = 'BOOKMARK_SAVE_SHIPPING_ADDRESS';
export const BOOKMARK_SAVE_PAYMENT_METHOD = 'BOOKMARK_SAVE_PAYMENT_METHOD';
export const BOOKMARK_EMPTY = 'BOOKMARK_EMPTY';
